/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PruebaFechaFrame.java
 *
 * Created on Aug 26, 2011, 10:55:26 PM
 */

package fechaspackage;

/**
 *
 * @author Fernando Carbajal
 */
public class PruebaFechaFrame extends javax.swing.JFrame {

    /** Creates new form PruebaFechaFrame */
    public PruebaFechaFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboDay = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboMonth = new javax.swing.JComboBox();
        txtYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dateResultInt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica 1 Lenguajes de Programación");

        actionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fecha sin parámetros", "Fecha con tres parámetros enteros", "Fecha con mes como cadena", "Determinar si dos fechas son iguales" }));
        actionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione la operación a realizar");

        jLabel2.setText("Fecha 1");

        comboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDay.setEnabled(false);

        jLabel3.setText("Dia");

        jLabel4.setText("Mes");

        jLabel5.setText("Año");

        comboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboMonth.setEnabled(false);

        txtYear.setText("1950");
        txtYear.setEnabled(false);

        jLabel6.setText("Fecha resultante:");

        dateResult.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        dateResult.setText("sin fecha");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dateResultInt.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        dateResultInt.setText("sin fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(actionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtYear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(727, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(713, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateResult, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateResultInt, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateResultInt)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBoxActionPerformed
        // TODO add your handling code here:
        
        // check the selection to enable/disable fields
        switch(actionBox.getSelectedIndex())
        {
            case 0:     // fecha sin parámetros
                comboMonth.setEnabled(false);
                comboDay.setEnabled(false);
                txtYear.setEnabled(false);
                break;
                
            case 1:     // fecha con parámetros enteros
                comboMonth.setEnabled(true);
                comboDay.setEnabled(true);
                txtYear.setEnabled(true);
                break;
            
        }
    }//GEN-LAST:event_actionBoxActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    int opc = actionBox.getSelectedIndex();
    switch(opc)
    {
        case 0:     // fecha sin parámetros
            if(ValidateDate(opc))
            {
                Fecha date = new Fecha();
                PrintDates(date, true);
            }
            break;
            
        case 1:     // fecha con números enteros
            if(ValidateDate(opc))
            {
                int day = comboDay.getSelectedIndex() + 1;     // +1 xq el index comienza desde 0
                int month = comboMonth.getSelectedIndex() + 1;     // +1 xq el index comienza desde 0
                String yearStr = txtYear.getText();
                int year = Integer.parseInt(yearStr);                     
                Fecha date = new Fecha(day, month, year);
                PrintDates(date, true);
            }
            else 
                PrintDates(null, false);
            
            break;
        
    }
    
   
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new PruebaFechaFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Imprime las fechas
     * @param date objeto Fecha a imprimir
     * @param valid es fecha válida?
     */
    public void PrintDates(Fecha date, boolean valid)
    {
        if(valid)
        {
            dateResult.setText(date.FechaToString());
            dateResultInt.setText(date.FechaIntToString());
        }
        else
        {
            dateResult.setText("Fecha no válida");
            dateResultInt.setText("Fecha no válida");
        }
    }
    
    
    /**
     * Valida los datos que recoge como fechas
     * @param opc indica qué validación hacer
     * @return validDate determina si es una fecha válida
     */
    public boolean ValidateDate(int opc)
     {
         boolean validDate = true;                  
         
         int year;
         
         switch(opc)
         {
             case 0:    // fecha sin parámetros -> no hay nada que checar
                 break;
             case 1:    // fecha con números enteros
                 try    // checa si el año se pudo parsear
                 {
                     String yearStr = txtYear.getText();
                     year = Integer.parseInt(yearStr);                     
                     //dateResult.setText(yearStr);
                 }
                 catch(NumberFormatException ex)
                 {
                    dateResult.setText("Fecha no válida: " + ex.toString());
                    validDate = false;
                    break;
                 }
                 
                 if(year < 1)       // no se aceptan años negativos
                     validDate = false;
                 
                 break;
         }
         
         // case: negative numbers
         
         
         // case: not valid dates like feb 20 (check for bisiesto)
         
         return validDate;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionBox;
    private javax.swing.JComboBox comboDay;
    private javax.swing.JComboBox comboMonth;
    private javax.swing.JLabel dateResult;
    private javax.swing.JLabel dateResultInt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

}
